
MOUSEKEY_ENABLE = yes
MOUSEKEY_INTERVAL = 20
MOUSEKEY_DELAY = 0
MOUSEKEY_MAX_SPEED = 7
MOUSEKEY_TIME_TO_MAX = 40
MOUSEKEY_WHEEL_MAX_SPEED = 10
MOUSEKEY_WHEEL_INTERVAL = 100
MOUSEKEY_WHEEL_TIME_TO_MAX = 40
